services:
  - type: web
    name: evershop
    env: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production